### ISSUE TITLE
Suggested improvement to command retrieving version number

### ISSUE THREAD

**Issue by jonathanbossenger** [wp-cli/dist-archive-command#36]
Summary:

When running this command and using the plugin header example described in the WordPress Plugin handbook, the version number is not found and therefore not appended to the zip archive.

Steps to reproduce:

1. Create plugin using plugin header format described in the WordPress Plugin handbook - https://developer.wordpress.org/plugins/the-basics/header-requirements/
1. Run `wp dist-archive` command to create plugin archive

Because the Version in the header example does not have the trailing asterisk, the version number is not found in the plugin header.

As per this slack conversation around the issue - https://wordpress.slack.com/archives/C02RP4T41/p1547804432280500
@swissspidy suggested reusing/extracting the header parsing functionality used by the i18n command in core
@schlessera suggested it might be time to extract that to a `get_file_header` helper method, or similar.

**Comment by schlessera** [comment]
I was referring to something like `WP_CLI\Utils\get_file_header()`, not using the WP version.

**Comment by danielbachhuber** [comment]
Ah 👍

**Comment by santilin** [comment]
I am new to wp development and I would like to give a try to solve this. I have been able to setup a development environment (thanks @schlessera) and now I'm trying to reproduce the problem and hopefully make a PR.

**Comment by santilin** [comment]
I've created a PR: https://github.com/wp-cli/dist-archive-command/pull/37

Please, tell me if it is necessary to assert this here and in case it is not, I beg your perdon :)

**Comment by schlessera** [comment]
@santilin No need to reference it in here, but rather do it the other way around: Add a mention "Fixes #36" in the description of your pull request (just edit your description and add it to the end). This will show a reference in here, and also automatically close this issue as resolved once your PR is merged.

**Comment by danielbachhuber** [comment]
🚢
