### ISSUE TITLE
Empty space in path is not escaped

### ISSUE THREAD

**Issue by obiPlabon** [wp-cli/dist-archive-command#40]
## Bug Report

When the `$archive_file` path has an empty space it doesn't create any zip file. I fixed it locally by escaping.
Before: `$cmd = "zip -r {$archive_file} {$archive_base} {$excludes}";`
After: `$cmd = "zip -r '{$archive_file}' {$archive_base} {$excludes}";`

**Comment by schlessera** [comment]
Fixed via https://github.com/wp-cli/dist-archive-command/pull/41
