### ISSUE TITLE
How to exclude files or folders from being ignored in a .distignore file

### ISSUE THREAD

**Issue by zerozak100** [wp-cli/dist-archive-command#44]
I have this .distignore file

`.distignore`
`.git`
`.gitignore`
`composer.json`
`composer.lock`
`package.json`
`package-lock.json`
`yarn.lock`
`vendor`
`node_modules`
`frontend/*`
`!/frontend/build/`

I have noticed that, sadly, this does not behave like a normal .gitignore. Slashes at the beginning won't work so if I try to exclude a directory from being ignore the git way with ! it does not seem to work. Even if I remove the initial slash it won't work either. 

Is it even possible to do this any other way?

**Comment by swissspidy** [comment]
The `.distignore` logic is very simple and currently does not allow using `!` like that unfortunately. See:

https://github.com/wp-cli/dist-archive-command/blob/fbe2a2527ddcc02329a17680776de376bc1dba62/src/Dist_Archive_Command.php#L77-L90

**Comment by weaver-sharethis** [comment]
> Slashes at the beginning won't work so if I try to exclude a directory from being ignore the git way with ! it does not seem to work.

I was wondering why those directories kept getting included. Good to know.

**Comment by danielbachhuber** [comment]
> There is a decent PHP library that could be forked to address this issue: [inmarelibero/gitignore-checker](https://github.com/inmarelibero/gitignore-checker/). The problem with the library is that it hard-codes the `.gitignore` filename and then uses `private` and `final` in its code, preventing easy inheritance. (someone please enlighten me why anyone uses those in open source code).

@BrianHenryIE Before forking, could we first ask the author if they'd be open to accommodating our use case?

If so, we could `composer require` the library to this project.

**Comment by schlessera** [comment]
> someone please enlighten me why anyone uses those in open source code
This is considered best practice and ensures people only extend the code in the ways that were anticipated by the author. This avoids situations where the library maintainer is forced into situation where they are required to support use cases that they never wanted to support, just to not break existing code that did random extensions.

> Before forking, could we first ask the author if they'd be open to accommodating our use case?
Yes, +1 on that. If the use case is valid, there's a high chance the author might be willing to add support for it.

**Comment by HelloAlberuni** [comment]
I have this .distignore file

```
node_modules/
vendor/
.git
.github
.DS_Store
.distignore
*.map
.gitignore
.npmignore
package.lock.json
package-lock.json
webpack.config.js
blocks/src/blocks.js

blocks/src/block/**/*.js
!blocks/src/block/**/*.json
```

`blocks/src/block/**/*.js`
This code stated to ignore the .js files only but it also ingoring the .json file, which I don't want.

I've tried this
`!blocks/src/block/**/*.json`

But it doesn't work.

How can I solve this, any idea?

**Comment by swissspidy** [comment]
> This code stated to ignore the .js files only but it also ingoring the .json file, which I don't want.

That sounds like a bug we should fix!

> I've tried this `!blocks/src/block/**/*.json`
> 
> But it doesn't work.

Yeah exclusion with `!` is not yet supported, which this issue here is all about.

**Comment by HelloAlberuni** [comment]
Hi @swissspidy 

Thanks your comment. It would be great fix for the upcoming release of the package. Hopefully it will be fixed soon :)

**Comment by swissspidy** [comment]
@HelloAlberuni I just opened #77 to address the particular issue with the JS vs. JSON file.

**Comment by htazad** [comment]
Great! @swissspidy 

Thanks for the quick fix!
