### ISSUE TITLE
Allow for leading slashes in .distignore to anchor to the root

### ISSUE THREAD

**Issue by markjaquith** [wp-cli/dist-archive-command#47]
`.distignore` is very simplistic: it looks for those files **anywhere**.

Let's say you have a directory called `src` in your root, as many WordPress plugins do. Okay, so you add `src` to `.distignore`.

But now, if you have a `src` directory anywhere deeper in your hierarchy, that's gonna get stripped out. Oof.

It would be lovely if all the features of `.gitignore` were supported, but at the very least, it would be good if root-anchoring were allowed, so that rules meant for one specific file or directory do not get applied deep within your tree.

**Comment by BrianHenryIE** [comment]
PR #58 is my attempt at this issue. The tests don't pass for `tar` but I'm pretty sure the command is correct.

#44 is an issue about `.gitignore` syntax.

**Comment by BrianHenryIE** [comment]
FTR, this is merged and tests for it are at: https://github.com/wp-cli/dist-archive-command/pull/61/files#diff-bc3cf447ca345c23d51f480946d45e220768ce3d282623db6a8d8c1a31a8800cR206-R261

So it's ready to be closed. Maybe it's pending the next version bump?

**Comment by danielbachhuber** [comment]
🚢
