### ISSUE TITLE
Why is not using the symbol - hyphen to separate the name and version?

### ISSUE THREAD

**Issue by davidperezgar** [wp-cli/dist-archive-command#72]
I find the actual structure of name not usual. Now is:
`plugin-name.1.0.0.zip`

The normal structure that you can find anywhere is this:
`plugin-name-1.0.0.zip`

Is anywhere where we could set up this?

**Comment by davidperezgar** [comment]
Thanks @danielbachhuber .

**Comment by danielbachhuber** [comment]
@i-am-chitti Sounds great
