### ISSUE TITLE
Warnings when running wp dist-archive create

### ISSUE THREAD

**Issue by brianhogg** [wp-cli/dist-archive-command#95]
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

When running `wp dist-archive <dir>` with PHP 8.2, there's a bunch of warnings:

```
Deprecated: Creation of dynamic property Inmarelibero\GitIgnor^CeChecker\Model\GitIgnore\Rule::$gitIgnoreFile is deprecated in /Users/brianhogg/.wp-cli/packages/vendor/inmarelibero/gitignore-checker/src/Model/GitIgnore/Rule.php on line 46
```

**Describe how other contributors can replicate this bug**

- Run `wp dist-archive <dir>` on a machine with PHP 8.2

**Describe what you would expect as the correct outcome**

No warnings :)

**Let us know what environment you are running this on**

```
OS:	Darwin 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:12:25 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6030 x86_64
Shell:	/bin/zsh
PHP binary:	/usr/local/Cellar/php@8.2/8.2.18/bin/php
PHP version:	8.2.18
php.ini used:	/usr/local/etc/php/8.2/php.ini
MySQL binary:	/usr/local/bin/mysql
MySQL version:	mysql  Ver 8.1.0 for macos14.0 on x86_64 (Homebrew)
SQL modes:
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/Users/brianhogg/laravel/lifter2/wp-content/plugins
WP-CLI packages dir:	/Users/brianhogg/.wp-cli/packages/
WP-CLI cache dir:	/Users/brianhogg/.wp-cli/cache
WP-CLI global config:
WP-CLI project config:
WP-CLI version:	2.10.0
```

**Provide a possible solution**

Update the inmarelibero/gitignore-checker package, if there's a newer version.

**Comment by BrianHenryIE** [comment]
https://github.com/inmarelibero/gitignore-checker/pull/14
