### ISSUE TITLE
How to run composer install before make the dist archive?

### ISSUE THREAD

**Issue by davidperezgar** [wp-cli/dist-archive-command#97]
Hello!
I love this command and I'm using a lot. 
I'd need run composer before makes the dist archive. How could approach that?

**Comment by swissspidy** [comment]
Since it's just a fancy way of making a zip file, there isn't really any special way for doing that.

```
cd my-project
composer install
wp dist-archive .
```

**Comment by ernilambar** [comment]
This will also include the package which is not needed in production. So to avoid this, you can use separate folder as base folder to archive.

**Comment by davidperezgar** [comment]
Obviously I was thinking in the same command

**Comment by swissspidy** [comment]
WP-CLI is all about composability. If you want to run composer before zipping, then run composer before dist-archive. Why doesn't that work for you?

**Comment by ernilambar** [comment]
I added dist archive as composer dev dependency. That is why.

**Comment by davidperezgar** [comment]
No problem, thanks. I concatenate the command, and it working fine.

`composer update --no-dev --working-dir=wp-content/plugins/plugin && wp dist-archive wp-content/plugins/plugin ~/projects/ --filename-format={name}-{version}`
