### ISSUE TITLE
Option missing [--filename-format=<filename-format>]

### ISSUE THREAD

**Issue by Niloys7** [wp-cli/dist-archive-command#98]
Hi,
In this [article](https://developer.wordpress.org/cli/commands/dist-archive/#:~:text=%5B%2D%2Dfilename%2Dformat%3D%3Cfilename,name%7D.%7Bversion%7D%E2%80%9D%0A%E2%80%94), there is an option to include the version in the zip file name. 
But when I run `wp help dist-archive` I can see this option is missing `[--filename-format=<filename-format>]`

![CleanShot 2024-08-11 at 21 41 15](https://github.com/user-attachments/assets/57fc3ed2-6404-48bb-9ff1-8e3d83c0d482)

I also try to run this but getting an error

![CleanShot 2024-08-11 at 21 43 20](https://github.com/user-attachments/assets/0408d4d4-c126-4c2a-ba21-8e83c51f5d24)

**Comment by ernilambar** [comment]
Can you please check version of the command? Is it `3.0.1`?
You can check using following command `wp package list`.

**Comment by Niloys7** [comment]
The version was `dev-main` I just updated it to `stable`, and now it's showing the last parameter. 
Thanks @ernilambar
