### ISSUE TITLE
Add option to overwrite the zip file

### ISSUE THREAD

**Issue by amenk** [wp-cli/dist-archive-command#99]
## Feature Request

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).

**Describe your use case and the problem you are facing**

Steps to reproduce:

1. `wp dist-archive .`
2. Add an additional file manually to the dist archive (in real life, my build script added additional files I did not expect)
3. call `wp dist-archive .` again
4. The additional files are still in the ZIP - it's not created freshly

**Describe the solution you'd like**

When the dist archive already exists, it seems to not be recreated. An `--overwrite` option to fully recreate the ZIP would be good.

**Comment by GeoJunkie** [comment]
If the archive exists, a prompt is given:

```
Warning: Archive file already exists
/Users/taco/code/wp-cli-dev.zip
Do you want to skip or replace it with a new archive? [s/r]: r
Replacing

Success: Created wp-cli-dev.zip
```

The Zip file is updated and contains new files I added manually. If this is running inside a script, though, there isn't an option to choose as an option. The code for the prompt could be called/reused for a command-line option.
